// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import Preview from './Preview.vue'
import VueLivePreview from './VueLivePreview.vue'

// Export components individually
export { Preview, VueLivePreview }

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('Preview', Preview)
  Vue.component('VueLivePreview', VueLivePreview)
}

// Export the library as a plugin
export default { install: install }
